/**
 * Copyright © 2024 Fraawlen <fraawlen@posteo.net>
 *
 * This file is part of the Cassette Configuration (CCFG) library.
 *
 * This library is free software; you can redistribute it and/or modify it either under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the
 * License or (at your option) any later version.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
 * See the LGPL for the specific language governing rights and limitations.
 *
 * You should have received a copy of the GNU Lesser General Public License along with this program. If not,
 * see <http://www.gnu.org/licenses/>.
 */

/************************************************************************************************************/
/************************************************************************************************************/
/************************************************************************************************************/

#include <stdio.h>

#include <cassette/ccfg.h>

#include "config.h" /* generated by makefile */

/************************************************************************************************************/
/************************************************************************************************************/
/************************************************************************************************************/

#define _SAMPLE_CONFIG_PATH "/tmp/ccfg_sample"

/************************************************************************************************************/
/************************************************************************************************************/
/************************************************************************************************************/

static void _generate_source (void);
static void _print_resource  (ccfg_t *cfg, const char *namespace, const char *property);

/************************************************************************************************************/
/************************************************************************************************************/
/************************************************************************************************************/

/**
 * In this 1st example, a simple resource look-up is done after loading the configuration.
 */

int
main(void)
{
	ccfg_t *cfg;

	/* init */

	cfg = ccfg_create();

	_generate_source();

	/* operations */

	ccfg_push_source(cfg, _SAMPLE_CONFIG_PATH);

	if (!ccfg_load(cfg))
	{
		printf("configuration failed to load\n");
	}

	printf("namespace\tproperty\traw_values\n");
	printf("---------\t--------\t----------\n");

	_print_resource(cfg, "example-1", "values-1");
	_print_resource(cfg, "example-1", "values-2");
	_print_resource(cfg, "example-1", "values-3");
	_print_resource(cfg, "example-1", "whatever"); /* expected to not be found */
	_print_resource(cfg, "example-9", "values-1"); /* expected to not be found */

	/* end */

	if (ccfg_has_failed(cfg))
	{
		printf("configuration has failed during operation.\n");
	}

	ccfg_destroy(&cfg);

	return 0;
}

/************************************************************************************************************/
/* _ ********************************************************************************************************/
/************************************************************************************************************/

static void
_generate_source(void)
{
	FILE *f;

	if (!(f = fopen(_SAMPLE_CONFIG_PATH, "w")))
	{
		printf("sample configuration in %s could not be generated\n", _SAMPLE_CONFIG_PATH);
		return;
	}

	fprintf(f, "%.*s", examples_config_len, examples_config);

	fclose(f);
}

/* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -*/

static void
_print_resource(ccfg_t *cfg, const char *namespace, const char *property)
{
	printf("%s\t%s", namespace, property);

	ccfg_fetch(cfg, namespace, property);
	while (ccfg_pick_next_value(cfg))
	{
		printf("\t%s", ccfg_get_value(cfg));
	}

	printf("\n");
}
