/**
 * Copyright © 2024 Fraawlen <fraawlen@posteo.net>
 *
 * This file is part of the Cassette Configuration (CCFG) library.
 *
 * This library is free software; you can redistribute it and/or modify it either under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the
 * License or (at your option) any later version.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
 * See the LGPL for the specific language governing rights and limitations.
 *
 * You should have received a copy of the GNU Lesser General Public License along with this program. If not,
 * see <http://www.gnu.org/licenses/>.
 */

/************************************************************************************************************/
/************************************************************************************************************/
/************************************************************************************************************/

#include <cassette/ccfg.h>
#include <stdio.h>

#include "config.h" /* generated by makefile */

/************************************************************************************************************/
/************************************************************************************************************/
/************************************************************************************************************/

#define SAMPLE_CONFIG_PATH "/tmp/ccfg_sample"

/************************************************************************************************************/
/************************************************************************************************************/
/************************************************************************************************************/

static void generate_source (void);
static void print_resources (const char *namespace, const char *property);

/************************************************************************************************************/
/************************************************************************************************************/
/************************************************************************************************************/

static ccfg *cfg = CCFG_PLACEHOLDER;

/************************************************************************************************************/
/* MAIN *****************************************************************************************************/
/************************************************************************************************************/

/**
 * In this 1st example, a simple resource look-up is done after loading the configuration. If found, the 
 * values associated with the resource are printed to stdout.
 */

int
main(void)
{
	/* Setup */

	cfg = ccfg_create();

	generate_source();

	ccfg_push_source(cfg, SAMPLE_CONFIG_PATH);
	ccfg_push_param(cfg, "example_param", "value_from_executable");

	/* Operations */

	ccfg_load(cfg);

	printf("namespace\tprop\traw_values\n");
	printf("---------\t----\t----------\n");

	print_resources("example-1", "a");
	print_resources("example-1", "b");
	print_resources("example-1", "c");
	print_resources("example-1", "d");
	print_resources("example-1", "e");
	print_resources("example-1", "f");
	print_resources("example-1", "g");
	print_resources("example-1", "h");
	print_resources("example-9", "i"); /* expected to not be found */

	/* End */

	if (ccfg_error(cfg))
	{
		printf("Configuration parser failed during operation.\n");
	}

	return 0;
}

/************************************************************************************************************/
/* _ ********************************************************************************************************/
/************************************************************************************************************/

static void
generate_source(void)
{
	FILE *f;

	if (!(f = fopen(SAMPLE_CONFIG_PATH, "w")))
	{
		printf("Sample configuration in %s could not be generated\n", SAMPLE_CONFIG_PATH);
		return;
	}

	fprintf(f, "%.*s", examples_config_len, examples_config);
	fclose(f);
}

/* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -*/

static void
print_resources(const char *namespace, const char *property)
{
	printf("%s\t%s", namespace, property);

	ccfg_fetch(cfg, namespace, property);
	while (ccfg_iterate(cfg))
	{
		printf("\t%s", ccfg_resource(cfg));
	}

	printf("\n");
}
