/**
 * Copyright © 2024 Fraawlen <fraawlen@posteo.net>
 *
 * This file is part of the Cassette Configuration (CCFG) library.
 *
 * This library is free software; you can redistribute it and/or modify it either under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the
 * License or (at your option) any later version.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
 * See the LGPL for the specific language governing rights and limitations.
 *
 * You should have received a copy of the GNU Lesser General Public License along with this program. If not,
 * see <http://www.gnu.org/licenses/>.
 */

/************************************************************************************************************/
/************************************************************************************************************/
/************************************************************************************************************/

#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>

#include <cassette/ccfg.h>

#include "config.h" /* generated by makefile */

/************************************************************************************************************/
/************************************************************************************************************/
/************************************************************************************************************/

#define _SAMPLE_CONFIG_PATH "/tmp/ccfg_sample"
#define _N_SIMULATIONS       10

/************************************************************************************************************/
/************************************************************************************************************/
/************************************************************************************************************/

static void  _generate_source   (void);
static void *_simulation_thread (void *param);

/************************************************************************************************************/
/************************************************************************************************************/
/************************************************************************************************************/

/**
 * In this 2nd example, a multithreaded software simulator is mimicked. Each simulation, sitting in its own
 * thread, requires the same kind of variables to work with (in this example, the coordinates of something).
 * However, each simulation instance also requires randomized coordinate values to create a different output.
 *
 * In this scenario, each simulation thread will set up its own configuration and and provide an unique
 * parameter "sim_id". That parameter will then be used as a LCG seed. Thanks to that, during parsing, 'RAND'
 * tokens will be substituted to a different values in each thread. The parser opens the source files
 * exclusively in read-only mode, therefore multithreaded access to the same source is safe.
 */

int
main(void)
{
	pthread_t threads[_N_SIMULATIONS];

	unsigned int ids[_N_SIMULATIONS];

	/* init */

	_generate_source();

	/* run pseudo-simulations */

	for (unsigned int i = 0; i < _N_SIMULATIONS; i++)
	{
		ids[i] = i;
		pthread_create(threads + i, NULL, _simulation_thread, ids + i);
	}
	
	for (unsigned int i = 0; i < _N_SIMULATIONS; i++)
	{
		pthread_join(threads[i], NULL);
	}

	return 0;
}

/************************************************************************************************************/
/* _ ********************************************************************************************************/
/************************************************************************************************************/

static void
_generate_source(void)
{
	FILE *f;

	if (!(f = fopen(_SAMPLE_CONFIG_PATH, "w")))
	{
		printf("sample configuration in %s could not be generated\n", _SAMPLE_CONFIG_PATH);
		return;
	}

	fprintf(f, "%.*s", examples_config_len, examples_config);

	fclose(f);
}

/* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -*/

static void *
_simulation_thread(void *param)
{
	ccfg *cfg;

	unsigned int coords[3] = {0};
	unsigned int id;

	/* simulation config setup */

	cfg = ccfg_create();
	id  = *(unsigned int*)param;

	ccfg_push_source(cfg, _SAMPLE_CONFIG_PATH);
	ccfg_push_param(cfg, "sim_id", id);
	ccfg_load(cfg);

	ccfg_fetch(cfg, "example-2", "coordinates");
	for (unsigned int i = 0; i < 3 && ccfg_iterate(cfg); i++)
	{
		coords[i] = strtoul(ccfg_resource(cfg), NULL, 0);
	}

	/* simulation algorithm */

	printf(
		"sim %u -> x = %u, y = %u, z = %u\n",
		id,
		coords[0],
		coords[1],
		coords[2]);

	/* simulation end */

	ccfg_destroy(cfg);

	pthread_exit(NULL);
}
